[package]
name = "safe-hook"
version = "0.2.0"
edition = "2024"

[dependencies]
inventory = "0.3"
safe-hook-macros = { path = "../safe-hook-macros" }

[dev-dependencies]
criterion = { version = "0.6", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false

